add_newline = false

[character]
success_symbol = "[âœ](bold green)"

[python]
python_binary = "python3"

[git_status]
conflicted = "ğŸ’¢"
ahead = "ğŸğŸ’¨"
behind = "ğŸŒ¦ï¸"
diverged = "ğŸ’¥"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "âœ¨"
deleted = "ğŸ—‘ï¸"
